---

- hosts: all
  become: yes
  gather_facts: no
  roles:
    - create_domain_user
  vars:
    create: true
    user_mem_args_value: "{{ weblogic_servers[server].user_mem_args_value }}"
  tags: always
    
- name: ensure_ownership
  hosts: all
  become: True
  gather_facts: False
  roles:
    - ensure_ownership
  tags: always
    
- name: weblogic_operations
  hosts: all
  become: yes
  gather_facts: no  
  become_user: "{{ domain_account.username }}"
  roles:    
    - weblogic_operations
  vars:
    clean_invoked: true
    clean: true
    weblogic_node_manager_address: "{{ weblogic_servers[server].node_manager_address }}"
    weblogic_node_manager_port: "{{ weblogic_servers[server].node_manager_port }}"
  tags: clean
    