---

- name: node_manager_operations
  hosts: all
  become: yes
  gather_facts: no
  become_user: "{{ domain_account.username }}"
  roles:      
    - node_manager_operations
  vars: 
     start: true
     user_mem_args_value: "{{ weblogic_servers[server].user_mem_args_value }}"
     weblogic_node_manager_address: "{{ weblogic_servers[server].node_manager_address }}"
     weblogic_node_manager_port: "{{ weblogic_servers[server].node_manager_port }}"    
  tags: start     

- name: weblogic_operations
  hosts: all
  become: yes
  gather_facts: no
  become_user: "{{ domain_account.username }}"
  roles: 
    - weblogic_operations
  vars:
     start: true
     user_mem_args_value: "{{ weblogic_servers[server].user_mem_args_value }}"
     weblogic_node_manager_address: "{{ weblogic_servers[server].node_manager_address }}"
     weblogic_node_manager_port: "{{ weblogic_servers[server].node_manager_port }}"         
     weblogic_instance_name: "{{ weblogic_servers[server].instance_name }}"
     weblogic_instance_address: "{{ weblogic_servers[server].instance_address }}"
     weblogic_instance_port: "{{ weblogic_servers[server].instance_port }}"     
  tags: start    