---

- name: ensure_ownership
  hosts: all
  become: True
  gather_facts: False
  roles:
    - ensure_ownership
  tags: always    

- name: weblogic_modification build      
  hosts: all
  become: yes
  become_user: "{{ domain_account.username }}"
  gather_facts: no
  roles:
    - weblogic_modification
  vars:
    build: true
    weblogic_automata_binary: weblogic_automata
  tags: build

- name: weblogic_modification config
  hosts: all
  become: yes
  become_user: "{{ domain_account.username }}"
  gather_facts: no
  roles:
    - weblogic_modification
  vars:
    config: true
    weblogic_automata_binary: weblogic_automata
  tags: config

- name: weblogic_modification deploy
  hosts: all
  become: yes
  become_user: "{{ domain_account.username }}"
  gather_facts: no
  roles:
    - weblogic_modification
  vars:
    deploy: true
    weblogic_automata_binary: weblogic_automata
  tags: deploy
      
- name: ensure_ownership
  hosts: all
  become: True
  gather_facts: False
  roles:
    - ensure_ownership
  tags: always    
      